spring.application.name=beagi-backend

server.address=0.0.0.0
server.port=${PORT:8080}
spring.datasource.url=${BEAGI_DB_URL:jdbc:postgresql://localhost:5432/beagi_db}
spring.datasource.username=${BEAGI_DB_USERNAME:beagi_user}
spring.datasource.password=${BEAGI_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.include-message=always
beagi.security.admin.username=${BEAGI_ADMIN_USERNAME}
beagi.security.admin.password=${BEAGI_ADMIN_PASSWORD}