spring.application.name=beagi-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/beagi_db
spring.datasource.username=beagi_user
spring.datasource.password=beagi_local_123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true